
set fileformat=unix
set clipboard^=unnamed,unnamedplus  " Get Machine Clipboard

set guioptions=c
set guifont=Lucida_Console:h10:cDEFAULT
set nocompatible  " no vi-compatible
set ls=2          " always show status bar
set bs=2          " fix backspace issues
set rnu           " relative number
set number
set showcmd
set cursorline
set backspace=2
set hlsearch
set ignorecase
set ttyfast
set novisualbell
set noerrorbells
set showmatch
set nobackup
set nowritebackup
set nowrap
set tags=tags;
set colorcolumn=80
set spelllang=pt_br,en
set noswapfile
if has('termguicolors')
  set termguicolors
endif


" Set python location for neovim
let g:python3_host_prog = 'python'

" Disable polyglot by filetype
let g:polyglot_disabled = ['markdown']


" Map jj to ESC
imap jj <ESC> 
tnoremap jj <C-\><C-n>


" Folding code By Indentation
set foldmethod=indent
set foldlevel=99
set nofoldenable
"nnoremap <space> za  " Map space key to fold/unfold


" Allow plugins by file type (required for plugins!)
filetype plugin on
"filetype indent on

" Syntax and Colors
syntax enable

" Tabs and Spaces configuration
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4
"set autoindent



" ============================================================================
" Vim-plug initialization
let vim_plug_just_installed = 0
let vim_plug_path = expand('~/.vim/autoload/plug.vim')
if !filereadable(vim_plug_path)
    echo "Installing Vim-plug..."
    echo ""
    silent !mkdir -p ~/.vim/autoload
    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    let vim_plug_just_installed = 1
endif

" manually load vim-plug the first time
if vim_plug_just_installed
    :execute 'source '.fnameescape(vim_plug_path)
endif

" ============================================================================
" Active Plugins
call plug#begin('~/.vim/plugged')

Plug 'sainnhe/sonokai'
Plug 'sainnhe/gruvbox-material'
Plug 'morhetz/gruvbox'
Plug 'drewtempelmeyer/palenight.vim'
Plug 'SidOfc/mkdx'
Plug 'dhruvasagar/vim-table-mode' 
Plug 'preservim/nerdtree'
Plug 'sheerun/vim-polyglot'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'itchyny/lightline.vim'
Plug 'tpope/vim-fugitive'

call plug#end()

if vim_plug_just_installed
    echo "Installing Bundles, please ignore key map error messages"
    :PlugInstall
endif

" ============================================================================


" FUNCTIONS
" ---------

" REMOVE TRAILING WHITESPACES BEFORE SAVING
fun! <SID>StripTrailingWhitespaces()
    let l = line(".")
    let c = col(".")
    %s/\s\+$//e
    call cursor(l, c)
endfun


function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

function! GBASH()
  silent !clear
  execute "terminal " . "C:/PROGRA~1/Git/bin/bash.exe --login -i"
endfunction




" THEMES
" ---------

" LIGHTLINE
set laststatus=2
let g:lightline = {
  \   'colorscheme': 'jellybeans',
  \   'active': {
  \     'left':[ [ 'mode', 'paste' ],
  \              [ 'gitbranch', 'readonly', 'filename', 'modified' ]
  \     ]
  \   },
  \   'component_function': {
  \     'gitbranch': 'fugitive#head',
  \   }
  \ }

" GRUVBOX_MATERIAL
"set background=dark
"let g:gruvbox_material_background = 'hard'
"let g:gruvbox_material_palette = 'original'
"colorscheme gruvbox-material
"let g:lightline.colorscheme = 'gruvbox_material'

" GRUVBOX_MATERIAL
"set background=dark
"let g:lightline.colorscheme = 'gruvbox_material'
"let g:gruvbox_contrast_dark = 'hard'
"let g:gruvbox_contrast_light = 'hard'
"let g:gruvbox_bold = 0
"colorscheme gruvbox

" PALENIGHT
"set background=dark
"colorscheme palenight   
"let g:lightline.colorscheme = 'palenight'
"let g:palenight_terminal_italics=1

"SONOKAI
set background=dark
let g:sonokai_style = 'shusia'
let g:sonokai_cursor = 'purple'
let g:sonokai_enable_italic = 0
let g:sonokai_enable_bold = 0
let g:sonokai_disable_italic_comment = 1
colorscheme sonokai
let g:lightline.colorscheme = 'sonokai'
let g:sonokai_lightline_disable_bold = 1
let g:sonokai_better_performance = 1




" PLUGIN CONFIGS
" ==============

"DEOPLETE
" Disable autocompletion, if deoplete is used
"let g:jedi#completions_enabled = 0
" Whether to show function call signature
"let g:jedi#show_call_signatures = '0'
" let g:deoplete#enable_at_startup = 1


" Ansible-Vim
au BufRead,BufNewFile *.yml set filetype=yaml.ansible cc=100
let g:ansible_name_highlight = 'b'
let g:ansible_extra_keywords_highlight = 1
"let g:ansible_normal_keywords_highlight = 'Constant'
"let g:ansible_with_keywords_highlight = 'Comment'
let g:ansible_unindent_after_newline = 1
let g:ansible_attribute_highlight = "o"


" COC
"
" Use tab for trigger completion with characters ahead and navigate.
" Use command ':verbose imap <tab>' to make sure tab is not mapped by other plugin.
inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

" Use <c-space> to trigger completion.
inoremap <silent><expr> <c-space> coc#refresh()

" Use <cr> to confirm completion, `<C-g>u` means break undo chain at current position.
" Coc only does snippet and additional edit on confirm.
inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"

" Use `[c` and `]c` to navigate diagnostics
nmap <silent> [c <Plug>(coc-diagnostic-prev)
nmap <silent> ]c <Plug>(coc-diagnostic-next)

" Remap keys for gotos
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)

" Use <C-j> for jump to next placeholder, it's default of coc.nvim
let g:coc_snippet_next = '<c-j>'

" Use <C-k> for jump to previous placeholder, it's default of coc.nvim
let g:coc_snippet_prev = '<c-k>'


let g:coc_global_extensions = [
      \ 'coc-pyright',
      \ 'coc-snippets',
      \ 'coc-json'
      \ ]

map <C-n> :NERDTreeToggle<CR>
map <C-g><C-b> :call GBASH()<CR>
map <C-p><C-s> :term C:/PROGRA~1/Powershell/7/pwsh.exe<CR>



" AUTOSTART
"
" Set Tab width
autocmd FileType html setlocal shiftwidth=2 tabstop=2 softtabstop=2
autocmd FileType yaml.ansible setlocal shiftwidth=2 tabstop=2 softtabstop=2
autocmd FileType sh setlocal shiftwidth=2 tabstop=2 softtabstop=2

" Strip whitespaces before EOL
autocmd FileType yaml.ansible,python,conf,ansible_hosts autocmd BufWritePre <buffer> :call <SID>StripTrailingWhitespaces()

" Vim jump to the last position when reopening a file
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

" MKDX fix for vim
if !has('nvim')
  augroup MKDX
    au!
    au FileType markdown so $HOME/.vim/plugged/mkdx/ftplugin/markdown.vim
  augroup END
endif

" Remap Leader key
let mapleader = ","
