# If not running interactively, don't do anything
[[ "$-" != *i* ]] && return

# History Options
# Don't put duplicate lines in the history.
export HISTCONTROL=$HISTCONTROL${HISTCONTROL+,}ignoredups
#
# Ignore some controlling instructions
# HISTIGNORE is a colon-delimited list of patterns which should be excluded.
# The '&' is a special pattern which suppresses duplicate entries.
# export HISTIGNORE=$'[ \t]*:&:[fb]g:exit'
export HISTIGNORE=$'[ \t]*:&:[fb]g:exit:ls' # Ignore the ls command as well
# Whenever displaying the prompt, write the previous line to disk
export PROMPT_COMMAND="history -a"
# Date and Time in HISTORY
export HISTTIMEFORMAT="%d/%m/%y %T "

# Autocomplete with History when press up arrow
bind '"\e[A":history-search-backward'
# Ignore case on autocompletion
bind 'set completion-ignore-case on'


# Umask
#
# /etc/profile sets 022, removing write perms to group + others.
# Set a more restrictive umask: i.e. no exec perms for others:
# umask 027
# Paranoid: neither group nor others have any perms:
# umask 077

# Functions
#
# Some people use a different file for functions
# if [ -f "${HOME}/.bash_functions" ]; then
#   source "${HOME}/.bash_functions"
# fi
#


# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi


. ~/.bash_prompt
. ~/.bash_alias
