
" Vim SETTINGS
set fileformat=unix
set clipboard^=unnamed,unnamedplus  " Get Machine Clipboard

set nocompatible  " no vi-compatible
set ls=2          " always show status bar
set bs=2          " fix backspace issues
set rnu           " relative number
set number
set ai            " set autoindent
set showcmd
set cursorline
set backspace=2
set hlsearch
set ignorecase
set ttyfast
set novisualbell
set noerrorbells
set showmatch
set nobackup
set nowritebackup
set nowrap
set tags=tags;
set colorcolumn=80
set spelllang=pt_br,en
set noswapfile
set term=xterm-256color

set bg=dark

" MAPS
imap jj <ESC> " ESC on insert mode


" Folding code By Indentation
set foldmethod=indent
set foldlevel=99
nnoremap <space> za  " Map space key to fold/unfold


" Allow plugins by file type (required for plugins!)
filetype plugin on
filetype indent on

" Syntax and Colors
syntax enable
"color vitaminonec
"color gruvbox
color OceanicNext
"color molokai

" Tabs and Spaces configuration
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4
set autoindent

autocmd FileType html setlocal shiftwidth=2 tabstop=2 softtabstop=2
autocmd FileType htmldjango setlocal shiftwidth=4 tabstop=4 softtabstop=4
autocmd FileType javascript setlocal shiftwidth=4 tabstop=4 softtabstop=4
autocmd FileType yaml setlocal shiftwidth=2 tabstop=2 softtabstop=2



" ============================================================================
" Vim-plug initialization

let vim_plug_just_installed = 0
let vim_plug_path = expand('~/.vim/autoload/plug.vim')
if !filereadable(vim_plug_path)
    echo "Installing Vim-plug..."
    echo ""
    silent !mkdir -p ~/.vim/autoload
    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    let vim_plug_just_installed = 1
endif

" manually load vim-plug the first time
if vim_plug_just_installed
    :execute 'source '.fnameescape(vim_plug_path)
endif

" ============================================================================
" Active Plugins

call plug#begin('~/.vim/plugged')

Plug 'junegunn/vim-plug'
Plug 'pearofducks/ansible-vim' ", { 'do': 'cd ./UltiSnips; ./generate.py' }
Plug 'itchyny/lightline.vim'
Plug 'tpope/vim-fugitive'

call plug#end()

if vim_plug_just_installed
    echo "Installing Bundles, please ignore key map error messages"
    :PlugInstall
endif


" ============================================================================



" PLUGIN CONFIGS
" ==============

" Ansible-Vim
au BufRead,BufNewFile *.yml set filetype=yaml.ansible
"let g:ansible_name_highlight = 'b'
let g:ansible_extra_keywords_highlight = 1
let g:ansible_normal_keywords_highlight = 'Constant'
let g:ansible_unindent_after_newline = 1
let g:ansible_attribute_highlight = "o"

" LIGHTLINE
set laststatus=2
let g:lightline = {
  \   'colorscheme': 'jellybeans',
  \   'active': {
  \     'left':[ [ 'mode', 'paste' ],
  \              [ 'gitbranch', 'readonly', 'filename', 'modified' ]
  \     ]
  \   },
  \   'component_function': {
  \     'gitbranch': 'fugitive#head',
  \   }
  \ }

